"""empty message

Revision ID: 0fd5de1d5364
Revises: 39f9aa4983ad
Create Date: 2024-07-29 12:10:49.612482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd5de1d5364'
down_revision: Union[str, None] = '39f9aa4983ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tweets_owner_fkey', 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('tweets_owner_fkey', 'tweets', 'users', ['owner'], ['username'])
    # ### end Alembic commands ###
