"""empty message

Revision ID: 39f9aa4983ad
Revises: c2b9246dc3a6
Create Date: 2024-07-29 11:50:48.139306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f9aa4983ad'
down_revision: Union[str, None] = 'c2b9246dc3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_pp', sa.Boolean(), nullable=True))
    op.drop_column('users', 'has_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_image', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'has_pp')
    # ### end Alembic commands ###
