"""Add op_username to Tweets model

Revision ID: c37caaa09782
Revises: ef6f52ea3eb3
Create Date: 2024-07-30 11:55:18.378911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37caaa09782'
down_revision: Union[str, None] = 'ef6f52ea3eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('op_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'op_username')
    # ### end Alembic commands ###
