"""Add image_id to Tweets model

Revision ID: ef6f52ea3eb3
Revises: cb3221e4ec5e
Create Date: 2024-07-30 11:27:14.517167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6f52ea3eb3'
down_revision: Union[str, None] = 'cb3221e4ec5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('image_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'image_id')
    # ### end Alembic commands ###
